### ISSUE TITLE
Mod does not appear

### ISSUE THREAD

**Issue by lowburger** [PoloNX/SimpleModDownloader#1]
Hi, I try your app and download mod and extract but when open SimpleModManager mod is not appear. So I check SD card and can't find file anywhere. I try some different mods for Zelda and all same. Where is file disappear to? Thx

**Comment by lowburger** [comment]
Sorry I rush a bit, I find some mod in root of SD card. Issue is your app will not check if user changed mod directory on SimpleModManager parameters.ini

**Comment by PoloNX** [comment]
Hi thanks for your feedback

Zelda botw is not supported because it use bcml files.

The extract work like this 'if there are one romfs or exefs folder just extract it here : mods/game/ModName/contents/tid/romfs'

**Comment by PoloNX** [comment]
> Sorry I rush a bit, I find some mod in root of SD card. Issue is your app will not check if user changed mod directory on SimpleModManager parameters.ini

Oh I didn't know this option of SimpleModManager ! I'll try to deploy a fix fast

**Comment by lowburger** [comment]
Thx, yes we can change option
```
# folder where mods are stored
stored-mods-base-folder =
```

**Comment by PoloNX** [comment]
the format is :

path/to/folder

or 

/path/to/folder 

?

**Comment by lowburger** [comment]
> the format is :
> 
> path/to/folder
> 
> or
> 
> /path/to/folder
> 
> ?

Almost as your second one but final slash in end:

/path/to/folder/

**Comment by PoloNX** [comment]
Okay thanks. I will do a commit in ~15 minutes.

**Comment by PoloNX** [comment]
Can you try with this commit ? https://github.com/PoloNX/SimpleModDownloader/actions/runs/5298079719

**Comment by PoloNX** [comment]
I tested it and it's working. When you confirm me it I'll merge the commit

**Comment by lowburger** [comment]
I test and now work with different directory, thx your great work.

**Comment by PoloNX** [comment]
I will edit the release. Not a new release
