### ISSUE TITLE
Backing out of image preview puts me back at page one[BUG]

### ISSUE THREAD

**Issue by thinktech2go** [PoloNX/SimpleModDownloader#10]
**Describe the bug**
Backing out of image preview puts me back at page one

**To Reproduce**
1. Go to 'view any image of mod not on page one'
2. Click on 'B to back out'
3. Back on page one of mods

**Expected behavior**
If I clicked on a mod on page six, then went to view images. when I back out I should end up back on page six.

**Comment by PoloNX** [comment]
Thanks for the report, I will investigate soon

**Comment by PoloNX** [comment]
Hi I can't reproduce the issue. Are you sure steps are good ? 

https://github.com/PoloNX/SimpleModDownloader/assets/57038157/2950c68d-f935-4ea0-bbc4-0bb65649b2ae

(at the second try i searched "mario" to see if the issue happend with the search)

**Comment by TheMasterCoders** [comment]
He could also be using 1.0...
