### ISSUE TITLE
mod isn’t downloading

### ISSUE THREAD

**Issue by Diowboss** [PoloNX/SimpleModDownloader#13]
So I just modded my switch and i installed simple mod downloader and simple mod manager but the thing is the mod called inf cap dives for super Mario odyssey doesn’t install and i do have all the requirements I have 90dns downloaded and I have no clue why it isn’t downloading

**Comment by PoloNX** [comment]
Can you try with one other mod v

**Comment by Diowboss** [comment]
It works with another mod so it’s not the games fault

**Comment by PoloNX** [comment]
It's a mod which use exefs patches. I will see if in a future update I can support them.
