### ISSUE TITLE
[BUG] No Internet connection/ no mods available to download

### ISSUE THREAD

**Issue by abintro** [PoloNX/SimpleModDownloader#14]
**Describe the bug**
Seemingly no internet connection (while connected to wifi and other apps able to access internet)

**On which mod**
No mods are selectable.

**To Reproduce**
1. Go to SimpleModDownloader
2. Click on (any game)
3. No mods selectable
4. Go to update app menu
5. No internet access

**Expected behavior**
Mod selection and ability to check for/apply updates

**Switch:**
 - Atmosphere 1.5.4 FW 16.0.3 (tried downgrading to 16.0.2 but no luck)
 - SimpleModDownloader version 1.0.1

**Additional context**
No other apps have trouble connecting to internet. Tried 2.4 ghz connection as well as 5 ghz. DNS blocking only nintendo domains.

**Comment by PoloNX** [comment]
It's a weird issue I have to investiguate

**Comment by PoloNX** [comment]
IF someone have devkitpro installed and encounter this issue can you run SimpleModDownloader.nro with nxlink and send me the log file ?

**Comment by PoloNX** [comment]
Can you try with this build ?

**Comment by PoloNX** [comment]
normally it is fixed

**Comment by abintro** [comment]
> Can you try with this build ?https://github.com/PoloNX/SimpleModDownloader/actions/runs/5364895674

Trying this now. If you can give me some steps to get the log file I can do that no problem. Thanks for the quick response!

**Comment by PoloNX** [comment]
Just if it works say me. Else I'll give you steps

**Comment by abintro** [comment]
It works, thanks!
