### ISSUE TITLE
[BUG] Mod List allows next page on "R" when does not exist

### ISSUE THREAD

**Issue by spkats1** [PoloNX/SimpleModDownloader#15]
**Describe the bug**
Mod List can take you to a blank page when hitting "R" 

**Applicable**
Games with at least one mod

**To Reproduce**
1. Go to 'Mod List.'
2. Click on 'R' (or 'R' again)
4. See error 'You navigated to a page that does not exist'

**Expected behavior**
To roll back to "page 1" (or not change page at all)

**Screenshots**
N/A

**Switch:**
 - Horizon Os version (ex 16.0.3)
 - SimpleModDownloader version (ex 1.0.1)

**Comment by PoloNX** [comment]
I will deploy a fix soon

**Comment by PoloNX** [comment]
fixed in the last commit
