### ISSUE TITLE
wrong mod file [BUG]

### ISSUE THREAD

**Issue by Xmoncoco** [PoloNX/SimpleModDownloader#16]
**Describe the bug**
when you download a mod a file is created at the root named mods[game of the mod]

**To Reproduce**
install a mod 

**Expected behavior**
add a new entry to the mods folder

**Switch:**
 - Horizon Os version 16.0.3
 - atmosphère
 - mariko
 - SimpleModDownloader version 1,0,1

**Additional context**
I already have a mods file before using modDownkiader

**Comment by Xmoncoco** [comment]
I try to see where is the problem I see the extract.cpp there is 'sdmc:/' but I think we can change to 'sdmc/mods/' I will try it when I can figure out how to install DevKitPro

**Comment by PoloNX** [comment]
Hi, did you install SimpleModManager before the download ? Normally in this function 

```
    std::string getModInstallPath() {
        std::filesystem::path path(std::string("sdmc:/config/SimpleModManager/parameters.ini"));
        if(std::filesystem::exists(path)) {
            Ini * config = Ini::parseFile(path.string());

            for(auto const& option : config->options) {
                writeOption(option, false);
            }

            if (config->options.size() > 0) {
                std::cout << "\n";
            }

            for (auto const& section : config->sections) {
                writeSection(section);
            }

            IniOption * path = config->findFirstOption("stored-mods-base-folder");

            std::cout << path->key << " = " << path->value << "\n";
            return path->value;
        }
        return "/mods/";
    }
    ```
    
    If you don't have the file it does to /mods/

**Comment by Xmoncoco** [comment]
yes is wierd I try to uninstall simple mod manager and mods folder

**Comment by Xmoncoco** [comment]
ok that me sorry for the issue

**Comment by Xmoncoco** [comment]
ok that me sorry for the issue

**Comment by PoloNX** [comment]
OKay no problem
