### ISSUE TITLE
Support multi mod?

### ISSUE THREAD

**Issue by lowburger** [PoloNX/SimpleModDownloader#2]
It's possible support multi mod or cannot be done?

For example mod with many options and many romfs folder: https://gamebanana.com/mods/449206

Thx

**Comment by PoloNX** [comment]
It is going to merge all the romfs folders, isn't that what is being asked for?

**Comment by lowburger** [comment]
If merge then overwrite different mod with each other, so this won't work. For working it must produce all as different option.

Btw I check this mod and does not appear even in merged form: https://gamebanana.com/mods/450147 
Maybe because it say `RomFs` and not `romfs`?

**Comment by PoloNX** [comment]
I'll try to investigate, the problem with mods is that there is no standard architecture.
