### ISSUE TITLE
App crashes on start [BUG]

### ISSUE THREAD

**Issue by Alpha-IA** [PoloNX/SimpleModDownloader#20]
**Describe the bug**
The application doesn't start and crashes directly

**To Reproduce**
1. Install the .nro inside the sd:/switch/ folder
2. Launch hbmenu in full RAM mode
3. Start SimpleModDownloader

**Switch:**
 - Horizon Os version 16.0.3
 - Atmosphere v1.5.4
 - SimpleModDownloader version 1.0.2
 - hbmenu v3.5.1
 - nx-hbloader v2.4.3
 - FAT32 SdCard

**Additional context**
No settings.json exists in the config/ folder, meaning that the crash happen before the copy of the settings.json file
All my others hb apps work without problems (including SimpleModManager), only this one crashes

I have included the atmosphere's crash report
[01687986801_0100ea80032ea000.log](https://github.com/PoloNX/SimpleModDownloader/files/11900079/01687986801_0100ea80032ea000.log)

**Comment by Alpha-IA** [comment]
Downgrading to 1.0.1 and upgrading from within the app fixed the problem

**Comment by PoloNX** [comment]
I will try to investigate. It's surely one issue with the settings.json

**Comment by PoloNX** [comment]
I know. The folder config/SimpleModDownloader is not created if it doesn't exist. Try to create it manually

**Comment by jholden3249** [comment]
Negative. Does not fix issue for me.
![20240307_001621](https://github.com/PoloNX/SimpleModDownloader/assets/19718926/369a25a0-46e1-44b7-938d-bdaf9cd614ff)
![20240307_002027](https://github.com/PoloNX/SimpleModDownloader/assets/19718926/33492e8f-207e-425e-80cf-2ede3bcde730)


Fatal error from R plus Album. Crash from R plus game or menu forwarder.
