### ISSUE TITLE
Crashes on Launch OLED latest AMS & HEKATE

### ISSUE THREAD

**Issue by EXO5KELETON** [PoloNX/SimpleModDownloader#21]
Crashes on launch. Any more information that's needed I can provide.

**Comment by PoloNX** [comment]
I know. The folder config/SimpleModDownloader is not created if it doesn't exist. Try to create it manually

**Comment by EXO5KELETON** [comment]
Thanks I’ll give that a go when I’m with the switch thanks again

**Comment by 91ajames** [comment]
> I know. The folder config/SimpleModDownloader is not created if it doesn't exist. Try to create it manually

Thanks! That worked!

**Comment by PoloNX** [comment]
@EXO5KELETON 
try this build https://github.com/PoloNX/SimpleModDownloader/actions/runs/5412847811

**Comment by EXO5KELETON** [comment]
@PoloNX i will do buddy thank you I’m at work at the moment when I get in later tonight I’ll give it a go.

thank you

**Comment by seanhalim** [comment]
On OLED latest AMS still very buggy, 1.0.2. 
Brilliant Diamond (Luminescent) will freeze the switch requiring a hard reboot.

**Comment by PoloNX** [comment]
I think I have one idea on why there is a crash. The chat « & » in constant.hpp

**Comment by seanhalim** [comment]
> I think I have one idea on why there is a crash. The chat « & » in constant.hpp

I'm sorry what do you mean? Thank you for the reply btw
