### ISSUE TITLE
[BUG] Update the app doesn't check current version

### ISSUE THREAD

**Issue by spkats1** [PoloNX/SimpleModDownloader#23]
**Describe the bug**
You keep re-downloading the app even if you are on the same version.

This is a minor issue since the same screen displays both "Current version" and "Available version"

**To Reproduce**
1. Go to 'Update App'
2. Click on 'Download SimpleModDownloader'
3. repeat

**Expected behavior**
The app to check If currentVersion = availiableversion 
then to disable download link and grey out (or etc) the text

**Switch:**
 - Horizon Os version (ex 16.0.3)
 - SimpleModDownloader version (ex 1.0.1)

**Comment by PoloNX** [comment]
For me it's normal. I thought to remove the download button but I decided to let it
