### ISSUE TITLE
Kirby's Return To Dream Land Deluxe

### ISSUE THREAD

**Issue by spkats1** [PoloNX/SimpleModDownloader#24]
**Describe the bug**
The app instantly crashes when I try to get view available mods

**Game**
Kirby's Return To Dream Land Deluxe
TitleID : 01006B601380E000
GameBanana : 17438

**Details**
 - I open the app with full ram redirect (holding R button)
 - so far no issues with any other games
 - on unpatched Erista Switch
 - Horizon Os version (ex 16.0.3)
 - SimpleModDownloader version 1.0.1 & version 1.0.2

**Comment by PoloNX** [comment]
I think the char ' is a problem. I don't really know I'll investigate
