### ISSUE TITLE
[BUG] Crashes on launch

### ISSUE THREAD

**Issue by TheMasterCoders** [PoloNX/SimpleModDownloader#26]
**Describe the bug**
The app crashes on launch due to config/SimpleModDownloader not existing.

**On which mod**
No mod.

**To Reproduce**
1. Delete "config/SimpleModDownloader"
2. Launch "SimpleModDownloader"
3. See the error

**Expected behavior**
Works like normal.

**Screenshots**
No screenshots.

**Switch:**
 - Horison OS version "Whatever version that runs this hb app"
 - SimpleModDownloader 1.0.0 - 1.0.2

**Additional context**
Didn't happen to me. Can be fixed by simply creating the directory "config/SimpleModDownloader"

**Comment by PoloNX** [comment]
Yes I know this is a know issue. Check the last build in action tab

**Comment by TheMasterCoders** [comment]
Thanks! The last issue about this you just said the manual way, so I thought, why not just do it automatically?
[CLOSED]
