### ISSUE TITLE
Crashes at the Startup [BUG]

### ISSUE THREAD

**Issue by AmyRoseRose** [PoloNX/SimpleModDownloader#28]
This shit crashes whenever I try to launch it. I want to download Zelda's Ballad or the Linkle Mod for BOTW without having to use BCML Loader. I DO NOT WANT TO HAVE TO MERGE MODS BY HAND EVERY TIME.
![20230713_060205](https://github.com/PoloNX/SimpleModDownloader/assets/134152757/142d637f-b30b-47c2-8540-e76363c49c75)

**Comment by PoloNX** [comment]
I have the answer for you but I'll never give you it
