### ISSUE TITLE
[BUG] Incorrect links 

### ISSUE THREAD

**Issue by AlexChecker** [PoloNX/SimpleModDownloader#31]
**Describe the bug**
For some games thre are incorrect links to mods. I've encountered it with Hatsune Miku Project Diva Megamix. All mods from app actually used for Megamix+ and are incompatible with Megamix. 

**On which mod**
https://gamebanana.com/mods/413103

**To Reproduce**
1. Try to download any mod for Hatsune Miku Project Diva Megamix
2. Open link in browser
3. Opened page will be for Megamix+

**Expected behavior**
Should load mods from [this](https://gamebanana.com/games/7886) category

**Switch:**
 - Horizon Os version 16.0.0
 - SimpleModDownloader version 1.0.3

**Comment by PoloNX** [comment]
You can edit the file include/constants.hpp on GitHub to fix your issue
