### ISSUE TITLE
[BUG] Crash on mod search

### ISSUE THREAD

**Issue by lillyschulte** [PoloNX/SimpleModDownloader#33]
**Describe the bug**
When searching for mods by using the [Y} Search funtion the software crashes with the error message:
"The software was closed because an error accurred"
This occurred to me when searching for mods for Mario kart 8 deluxe.

**On which mod**
N/A

**To Reproduce**
1. Go to Simple mod downloader
2. Click on Mario kart 8 Deluxe
3. Click on [Y] Seach
4. Enter seach query
5. Press Search
6. See error

**Expected behavior**
Show search results based on search query

**Screenshots**

**Switch:**
 - Atmosphere version 1.5.4E
 - Hekate 6.0.5
 - Firmware 16.0.3
 - Mario Kart version 2.4.0
 - SimpleModDownloader version 1.0.3

**Additional context**
This somehow doesnt occure when searching for "Shrek".
This made me think that it maybe had something to do with the software not being able to handle when there are no results on gamebanana. Tested this out by searching for a mods keywords, that i know exists on gamebanana(Example used:https://gamebanana.com/mods/172093. Keyword used: Miata& Miata ND). Yet the software still crashes.

**Comment by PoloNX** [comment]
Thanks for the report. I will investigate in the day

**Comment by PoloNX** [comment]
It's a stupid bug added here : https://github.com/PoloNX/SimpleModDownloader/commit/e7714e9e7cb60ad3c145be5f2b715a0960f925c4

Fixed in the latest commit
