### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BDMCGaming** [PoloNX/SimpleModDownloader#35]
**Describe the bug**
Crashes upon clicking Mega Man 11

**On which mod**
Mega Man 11

**To Reproduce**
1. Go to Downloads
2. Click on 'Mega Man 11'

**Expected behavior**
It should show me the mods for Mega Man 11

**Switch:**
 - Horizon Os version 16.0.03
 - SimpleModDownloader version 1.0.3

**Comment by PoloNX** [comment]
Hi. Can you try with the last build in "action" tab ?

**Comment by BDMCGaming** [comment]
It loads into the mod list, but no mods show.
