### ISSUE TITLE
[BUG] Small issue when update app

### ISSUE THREAD

**Issue by lowburger** [PoloNX/SimpleModDownloader#37]
This only small issue, when update app using in app feature nro will not place on original location. For me I like to keep them on folders for alphabetical.

Example:

nro store in `switch/SimpleModDownloader/SimpleModDownloader.nro`

use in app update

when finish nro now at `switch/SimpleModDownloader.nro` and old folder became empty

Thx

**Comment by PoloNX** [comment]
I'll try to fix that. If the homebrew is in switch/folder it will keep it In this folder

**Comment by PoloNX** [comment]
Removed the ability to update the app. Because of hb-appstore exists
