### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sskyNS** [PoloNX/SimpleModDownloader#38]
**Describe the bug**

**On which mod**
Paste the link of the mod here

**To Reproduce**

**Expected behavior**

**Screenshots**

**Switch:**
 - Horizon Os version (ex 16.0.3)
 - SimpleModDownloader version (ex 1.0.1)

**Additional context**

**Comment by PoloNX** [comment]
?

**Comment by sskyNS** [comment]
It seems that in the latest 16.1.0 system version, after running it once, it never opens again. It will prompt a software error, no matter how many times I repeat the installation, it seems that it can only be opened the first time it works (without an Internet connection), once it is connected to the Internet, it can no longer be opened, and it says the above error.

**Comment by PoloNX** [comment]
This issue is just on 16.1.0 ? And other homebrews have the same issue ?

**Comment by sskyNS** [comment]
Thank you for such a quick reply, thank you very much. I tried it on both of my machines, they connected to the network, one was 16.0.3 and one was 16.1.0, both of which ran once and then generated errors. The code is 0100000000001D and if it enters from other frontends, it will produce [Software error has been closed] I did not find this error in other homebrews. This is a great NRO and I hope you can assist me with it

**Comment by sskyNS** [comment]
![Uploading IMG_4555.jpeg…]()

**Comment by sskyNS** [comment]
Okay, let me go back and open my computer to check my Switch folder. In principle, I have placed an nro file, and the json file under /config may be generated automatically after running it?

**Comment by sskyNS** [comment]
![IMG_4559](https://github.com/PoloNX/SimpleModDownloader/assets/121209531/a563bdd5-2941-465e-83be-5c678c16e749)

**Comment by TheMasterCoders** [comment]
Chinese may not be implemented yet. I recommend changing your language
