### ISSUE TITLE
When I download a smash mod and go to simplemodmanager it says there are no mods

### ISSUE THREAD

**Issue by Minecraftplayer20** [PoloNX/SimpleModDownloader#40]
**Describe the bug**
When I download a smash mod from simplemoddownloader and go to simplemodmanager it says there are no mods there it only works for games that i have inserted

**On which mod**
Any mod

**To Reproduce**
1. Go to simplemoddownloader
2. download smash mod
3. go to simplemodmanager
4. see error no mods for smash

**Expected behavior**
to see two minecraft mods to install

**Screenshots**
none

**Switch:**
 - Horizon Os version 1.7.0.0|AMS 1.6.1|S
 - SimpleModDownloader version 1.0.3

**Comment by TheMasterCoders** [comment]
Check if it's on the Root of the drive.

**Comment by Minecraftplayer20** [comment]
> Check if it's on the Root of the drive.

On the root of my sd card I see a folder named mods but I only see mario kart 8 no minecraft

**Comment by Minecraftplayer20** [comment]
> Maybe minecraft mods aren’t supported. I don’t know if they use romfs system 

Im also having the same problem with smash im using a pirated copy of the game

**Comment by PoloNX** [comment]
> > Maybe minecraft mods aren’t supported. I don’t know if they use romfs system 
> 
> Im also having the same problem with smash im using a pirated copy of the game

You have to use the last build in actions tab and arcropolis

**Comment by Minecraftplayer20** [comment]
> > > Maybe minecraft mods aren’t supported. I don’t know if they use romfs system 
> > 
> > Im also having the same problem with smash im using a pirated copy of the game
> 
> You have to use the last build in actions tab and arcropolis

What is arcropolis? where is the actions tab?

**Comment by Minecraftplayer20** [comment]
> > > > Maybe minecraft mods aren’t supported. I don’t know if they use romfs system 
> > > 
> > > Im also having the same problem with smash im using a pirated copy of the game
> > 
> > You have to use the last build in actions tab and arcropolis
> 
> What is arcropolis? where is the actions tab?
> 

I installed arcropolis but i have no idea where the actions tab is

**Comment by PoloNX** [comment]
Here : https://github.com/PoloNX/SimpleModDownloader/suites/16981780318/artifacts/970198106

**Comment by Minecraftplayer20** [comment]
> Here : https://github.com/PoloNX/SimpleModDownloader/suites/16981780318/artifacts/970198106

Its a 404

**Comment by PoloNX** [comment]
Check here and go on the SimpleMidDownloader https://github.com/PoloNX/SimpleModDownloader/actions/runs/6440445455

**Comment by Minecraftplayer20** [comment]
> > Here : https://github.com/PoloNX/SimpleModDownloader/suites/16981780318/artifacts/970198106
> 
> Its a 404

Nvm it downloaded something

**Comment by Minecraftplayer20** [comment]
I enabled use arcropolis for smash mods but when I download a smash mod and go to the mod manger it isn't there all I see is mods for super Mario Odyssey

**Comment by PoloNX** [comment]
It doesn't appear in SimpleModManager but in acropolis normally. I don't know how it works

**Comment by Minecraftplayer20** [comment]
> It doesn't appear in SimpleModManager but in acropolis normally. I don't know how it works

is acropolis supposed to be a application you can open in homebrew channel?

**Comment by PoloNX** [comment]
I don't know check on google if there is a guide

**Comment by Minecraftplayer20** [comment]
> I don't know check on google if there is a guide

oh ok

**Comment by Minecraftplayer20** [comment]
supposed to acropolis is supposed to replace the eshop section on smash to the mods section but it doesent do that

**Comment by Minecraftplayer20** [comment]
im reading a guide right now

**Comment by Minecraftplayer20** [comment]
I figured out I need skyline

**Comment by Minecraftplayer20** [comment]
ok the mods finally work
