### ISSUE TITLE
Please add support for .rar files

### ISSUE THREAD

**Issue by VillainousSsnake** [PoloNX/SimpleModDownloader#42]
Please add support for downloading and installing mods that are compressed in the .rar format.

**Comment by PoloNX** [comment]
Already tried but I can't. If you know how to do it you can try to do a pull request

**Comment by VillainousSsnake** [comment]
Is the issue extracting them or downloading them?

**Comment by PoloNX** [comment]
It's in the extraction. I use libarchive but the rar is unsupported. I already tried the lib rarlib but the extraction fail

**Comment by VillainousSsnake** [comment]
The newest version of libarchive supports rar format fully, maybe you could update the library?

**Comment by PoloNX** [comment]
I’ll do this in saturday

**Comment by PoloNX** [comment]
I made a pr I have to wait now. Idk how to build without this pr without a libarchive sub dir in the project.

**Comment by PoloNX** [comment]
https://github.com/devkitPro/pacman-packages/pull/327

**Comment by PoloNX** [comment]
Can you try the following build ? @VillainousSsnake 
https://github.com/PoloNX/SimpleModDownloader/actions/runs/6988080435

**Comment by PoloNX** [comment]
Try the following build instead : 
[SimpleModDownloader.zip](https://github.com/PoloNX/SimpleModDownloader/files/13464324/SimpleModDownloader.zip)

**Comment by VillainousSsnake** [comment]
> Try the following build instead : 
> 
> [SimpleModDownloader.zip](https://github.com/PoloNX/SimpleModDownloader/files/13464324/SimpleModDownloader.zip)
> 
> 

Okay I'll try that. I just need to inject atmosphere into my switch

**Comment by VillainousSsnake** [comment]
It works! Thank you so much!

**Comment by VillainousSsnake** [comment]
Please add this to the latest release.

**Comment by PoloNX** [comment]
I'll do a release later when all bugs will be fixed

**Comment by VillainousSsnake** [comment]
> I'll do a release later when all bugs will be fixed 

Okay
