### ISSUE TITLE
Adding .bnp support to simple mod downloader 

### ISSUE THREAD

**Issue by T1XOL** [PoloNX/SimpleModDownloader#45]
I have had a lot of trouble with using bcml for my breath of the wild mods and decided to move over here for my mods as it seamed to be quite easy to use, until i realized that i doesn't support the bnp file type which is used majorly in botw mods. Now i don't know if it's possible but maybe in a future update it could be added to the already great mod downloader and mod manager package. Thanks

**Comment by PoloNX** [comment]
I don’t really know how bcml works but it uses romfs of botw. It would be hard to adapt and honestly I don’t have the time/motivation for this. But if someone feel free to do
