### ISSUE TITLE
[BUG] Downloading Tears of the Kingdom mod crashes atmosphere entirely

### ISSUE THREAD

**Issue by miteduk3** [PoloNX/SimpleModDownloader#47]
Downloading mod crashes atmosphere

Tears of the Kingdom:
pretty sure ANY mod crashes

To Reproduce
1. Go to download Tears of Kingdom mod
2. Click on ANY mod and press download
3. Downloading...
Did the download part finish? (1/3) 
Cool! *CRASH*

(it crashes atmosphere after finishing the downloading phase)

Switch:
 - Atmosphere (17.0.1)
 - SimpleModDownloader (1.1.0)
 - Switch CFW (17.0.1)

Other bit of info, whenever i open simple mod downloader and then try to exit it (that be from pressing the exit button, or from pressing the home button and trying to press close) this always freezes the switch and makes it inoperable. 

Holding down home button and pressing sleep mode, nothing happens, holding down power button, tapping power options, restart/power off, nothing happens, no button inputs work either in this mode. 

Thus forcing me to hold down the power button till my switch turns off, turning it back on to make sure it still works, then rebooting back into hekate, and then back to atmosphere.

**Comment by PoloNX** [comment]
Thanks for reporting the bug. I'll try to fix it
