### ISSUE TITLE
[BUG] cant download some mods

### ISSUE THREAD

**Issue by Kris123454** [PoloNX/SimpleModDownloader#53]
You cant download mods that are in .dat or .dtt (.pkz works) when i press the download nothing happens

**Comment by PoloNX** [comment]
Is it an archive extension ?

**Comment by Kris123454** [comment]
> Is it an archive extension ?

Yeah its in .zip

**Comment by PoloNX** [comment]
Can you respect the issue template please ? Without more infos I can't do anything

**Comment by Yeetov** [comment]
Doesn't download mods even though it requests.
![SimpleModDownloader_20240316_111127_00](https://github.com/PoloNX/SimpleModDownloader/assets/69159547/f6374529-1832-4fd6-8f11-ef2ee3d411d9)

**Comment by PoloNX** [comment]
It’s because the mod isn’t supported (doesn’t contain a romfs/ folder) I should make a popup

**Comment by Yeetov** [comment]
No romfs is fine for arcropolis (smash mods)

**Comment by PoloNX** [comment]
Didn't know it was a smash bros mod  will fix it

**Comment by PoloNX** [comment]
fixed in the last commit @Yeetov
