### ISSUE TITLE
Update HBStore Listing

### ISSUE THREAD

**Issue by Yorisoft** [PoloNX/SimpleModDownloader#54]
**Is your feature request related to a problem? Please describe.**
Sort of. The HBStore currently has version 1.0.0 listed. I think this is causing crashes when downloading mods. The update might fix. 

**Describe the solution you'd like**
Update the app on HBStore to the latest version. 

**Describe alternatives you've considered**
Taking it down? That would prevent folks from installing an outdated version. Not sure tbh. 

**Additional context**
no.

**Comment by PoloNX** [comment]
Hi. I don't maintain the hb appstore. Maybe you should ask to the owner of hb AppStore

**Comment by Yorisoft** [comment]
Ahh gotcha. Thought it was an open marketplace. Thanks!
