### ISSUE TITLE
[BUG] .rar archive files not extracting

### ISSUE THREAD

**Issue by nyooNyoo** [PoloNX/SimpleModDownloader#55]
**Describe the bug**
Mods packaged in ,rar file format don't extract properly (stuck at 0% extraction progress)

**On which mod**
https://gamebanana.com/mods/450057 (an example)

**Log file**
https://pastebin.com/6maEVgGz

**To Reproduce**
1. Download any .rar formatted download
2. Witness the forever 0%

**Expected behavior**
The app should detect the archive format and extract accordingly, or at the very least raise an error to the user that the detected format is not supported

**Screenshots**
Not really needed

**Switch:**
 - Atmosphere 1.6.2 | Firmware 17.0.1
 - SimpleModDownloader version 2.0.0

**Comment by PoloNX** [comment]
Thanks for finding this issue. I'll investigate it

**Comment by PoloNX** [comment]
You can try the last build in the action tabs and it will now works @nyooNyoo
