### ISSUE TITLE
Weird thing. Don't know how to explain it.

### ISSUE THREAD

**Issue by 8Gohl** [PoloNX/SimpleModDownloader#56]
So I was going to make a bug that I couldn't update to 2.0.0 because it would crash, it said go to the log files and paste here, I went to config but another smd was in that folder and that was the new 2.0.0 smd. when i tried to open it, it opened smd but the UI and everything looked different and this is the new update. I downloaded a mod and it worked, every other time I tried to download a specific mod, the old smd would crash. the smd I have favorited (1.1.0)  is different and buggier than the one in this config folder (2.0.0) anyone know why it's in the config folder and how I could move it to the sdmc:/switch directory?

**Comment by 8Gohl** [comment]
Ok update, the app is gone from the config directory and after unfavoriting smd, it switched to the 2.0.0 version. What is even going on.

**Comment by 8Gohl** [comment]
Uninstalled and reinstalled from the hb app store and now I'm stuck again on 1.1.0 dev with no 2.0.0 in the config version.

**Comment by PoloNX** [comment]
Hi. The updater from 1.1.0 is very buggy. Please update it manually

**Comment by PoloNX** [comment]
Yes

**Comment by 8Gohl** [comment]
Ok thanks

**Comment by 8Gohl** [comment]
Also when I had the 2.0.0 version I tried to get a mod, so I searched it, but the first result wouldn't download. Like the download button could be pressed but it wouldn't do anything. I tried the second search result and the download button worked.

**Comment by 8Gohl** [comment]
Oh thank you

**Comment by PoloNX** [comment]
You should do it manually with one computer and gamebanana
