### ISSUE TITLE
[BUG] How to delete mods without the mods

### ISSUE THREAD

**Issue by EDGARIN350** [PoloNX/SimpleModDownloader#57]
**Describe the bug**
It's a little difficult to explain what happened to me, but basically in summary I tried to install some mods to smash bros and when I put the mods the game crashes so I decided to delete the mods via ftp, the problem is that I think the mods are still running even when I deleted them, so the truth is that I do not know what to do to remove them completely since I tried to put them back into the simple mod manager and give it to disable but the game continues to crash.

**Expected behavior**
I was hoping that when I removed the ftp mods the game would be back to normal.

**Switch:**
 - Atmoshphere version 1.6.2
 - SimpleModDownloader version 2.0

**Additional context**
![Super_Mario_Bros _Wonder_20240317_200913_00](https://github.com/PoloNX/SimpleModDownloader/assets/92487113/53d4700b-5357-4e6b-a24f-fa9663326360)

**Comment by PoloNX** [comment]
Hi. Smash bros use arcropolis. Try to delete ultimate/ folder at the root of the sdcard

**Comment by PoloNX** [comment]
normally fixed in https://github.com/PoloNX/SimpleModDownloader/commit/4fbcde8b2f6b24b2da7392589a0f41beac46b3c1
