### ISSUE TITLE
[ENHANCEMENT] Allow multiple games to show in the mod manager

### ISSUE THREAD

**Issue by Yeetov** [PoloNX/SimpleModDownloader#59]
**Is your feature request related to a problem? Please describe.**
There is only 1 game shown when clicking on installation.

**Describe the solution you'd like**
Make multiple mod folders for games in the mod manager's path

**Comment by PoloNX** [comment]
I'm not the creator of SimpleModManager which is the homebrew used to install mods. Make this feature request on his repo
