### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by Wildtimo** [PoloNX/SimpleModDownloader#60]
**Is your feature request related to a problem? Please describe.**
My mod patches the game and dlc but it only extracts the game patch and thinks its done when there's another folder with romfs in it.

**Describe the solution you'd like**
detect multiple folders with romfs and copy all

**Additional context**
mod link: https://gamebanana.com/mods/505273

**Comment by PoloNX** [comment]
Thanks for the report. I have to see how to add dlc support because the title id of the dlc is different

**Comment by Wildtimo** [comment]
I found a work around for my game because the dlc seems to work exactly like layeredfs, I was able to pack the dlc overwrites in the base titleid.

**Comment by PoloNX** [comment]
Thanks. Maybe you can share the old .zip here ?

**Comment by Wildtimo** [comment]
[super_mamada_galaxial_xdddd_weon_65124.zip](https://github.com/PoloNX/SimpleModDownloader/files/14883462/super_mamada_galaxial_xdddd_weon_65124.zip)
this should be it.

**Comment by PoloNX** [comment]
I searched and I didn't find a way to get the title id of the dlc when I scrap games.
