### ISSUE TITLE
[BUG] Download Button does't work on certain games 

### ISSUE THREAD

**Issue by youmademeswallowmygum** [PoloNX/SimpleModDownloader#61]
**Describe the bug**
On many games (Super Smash Bros. Ultimate, Skyrim, etc.) i've found a bug on when clicking on a mod and clicking"download" nothing happens. I tried manually adding the Title ID folder of the games into /atmosphere/contents/ however I still ran into the same bug. I also tried the previous version of the app searching for a workaround, in which the download button did work and while it appeared to be downloading when I check the files nothing has been downloaded. 

**To Reproduce**
1. Go to 'Simple Mod Downloader'
2. Click on 'Super Smash Bros. Ultimate'
3. Click on a mod (any mod seems to have the same bug but for these purposes ill name one) Fierce Deity MewTwo 
    https://gamebanana.com/mods/339100
4. Click on 'Download'

**Expected behavior**
When clicking download, nothing happens.

**Switch:**
 - Horizon Os version: 17.01
 - SimpleModDownloader version: 2.00

**Comment by PoloNX** [comment]
Hi. Can you try the latest build in the action tab ?

**Comment by youmademeswallowmygum** [comment]
Hi, it shows that it downloads now however im not seeing it downloaded anywhere in the files

**Comment by PoloNX** [comment]
If it's a smash bros mod it uses the default directory of Arcropolis

**Comment by seulgiism** [comment]
same problem here.

**Comment by PoloNX** [comment]
Did you check the default directory or arcropolis?
