### ISSUE TITLE
[FREEZE]the console freeze when i type Y to search

### ISSUE THREAD

**Issue by dragonis2012** [PoloNX/SimpleModDownloader#65]
freeze when trying to go on search
when i want to go on search the entire console freeze

no mod

no log

To Reproduce
1. Go to 'tears of the kingdom'
2. Click on 'Y'

Switch:
 - atmosphere  version 17.0.1
 - SimpleModDownloader version 2.0.0

**Comment by PoloNX** [comment]
Can you try the latest build in action tab

**Comment by BerrieBuffel** [comment]
I have the same issue suddenly, I didn't have the issue a few days ago

**Comment by PoloNX** [comment]
Can you send me your logs ?

**Comment by BerrieBuffel** [comment]
I'll send them in a few hours

**Comment by PoloNX** [comment]
Closed due to inactivity
