### ISSUE TITLE
Impossible to use latest version with atmosphere 17.0.1

### ISSUE THREAD

**Issue by dlearin** [PoloNX/SimpleModDownloader#67]
Any momment I use A to select a game, it show to me the following error:

P.D: Im using the latest release.

![photo1715785303](https://github.com/PoloNX/SimpleModDownloader/assets/9204252/883da541-e772-4988-a948-85320efb100e)

**Comment by PoloNX** [comment]
Hi. Can you test the latest build in the action tab ?

**Comment by dlearin** [comment]
> Hi. Can you test the latest build in the action tab ?

Totally fine with the latest one in action. Thanks!
