### ISSUE TITLE
[BUG] Can not download mods

### ISSUE THREAD

**Issue by sdal** [PoloNX/SimpleModDownloader#69]
After pressing on a game I want to download a mod for:
1. In applet mod atmosphere crashes.
2. In game mode error pops saying app's closed because of some error. 

**On which mod**
Any game i try to download something for.

**Log file**
[crashlogs.zip](https://github.com/PoloNX/SimpleModDownloader/files/15366433/crashlogs.zip)n

**To Reproduce**
1. Open hbmenu in any mode.
3. Open SimpleModDownloader
4. Touch or select with A any game to see a list of mods.
5. Get an error

**Expected behavior**
At least to see a list of mods.

**Switch:**
 - Horizon Os version 18.0.0
 - SimpleModDownloader version 2.0.0

**Comment by PoloNX** [comment]
Can you try the build in the action tab ?

**Comment by ominixisboss** [comment]
> Can you try the build in the action tab ?

how do i try the latest build?

**Comment by sdal** [comment]
Okay, the solution was simple

**Comment by PoloNX** [comment]
@sdal @ominixisboss can you test this build ?

**Comment by sdal** [comment]
Yes, I've tried the latest build from 17 hours ago. System still crashes.

**Comment by PoloNX** [comment]
> Yes, I've tried the latest build from 17 hours ago. System still crashes.

Just made a fix. A new feature just broke an older one

**Comment by PoloNX** [comment]
![2024052021351800](https://github.com/PoloNX/SimpleModDownloader/assets/57038157/61217b85-0f09-4016-89cf-224065492dae)
you should get this

**Comment by sdal** [comment]
Yep, now it is working correctly. Thank you!
