### ISSUE TITLE
[BUG] BOTW uses wiiu version

### ISSUE THREAD

**Issue by BerrieBuffel** [PoloNX/SimpleModDownloader#73]
BOTW uses WiiU version mods Instead of switch mods

**To Reproduce**
1. open simple mod downloader
2. Click on Breath of the wild
3. Says breath of the wild wiiu on the top of the screen

Expected to use switch version of mods

![IMG_20240528_122419.jpg](https://github.com/PoloNX/SimpleModDownloader/assets/121257724/de3c0878-b1f5-4c1b-99da-76667d917cce)

**Switch:**
 - Horizon Os version (18.0.1)
 - SimpleModDownloader version (2.0.0)

**Comment by PoloNX** [comment]
Thanks for the report. I will fix it. But sadly botw use bcml and SimpleModDownloader isn’t compatible with bcml

**Comment by BerrieBuffel** [comment]
there is a bnp to switch program on gamebanana

**Comment by PoloNX** [comment]
Will add the support of botw one day

**Comment by BerrieBuffel** [comment]
Thanks
