### ISSUE TITLE
[ENHANCEMENT] Change path of extraction

### ISSUE THREAD

**Issue by zrm9901** [PoloNX/SimpleModDownloader#76]
Im trying to get this to extract to a different directory with a different path structure where it would be {game name} - {mod name} / {title id} / Romfs in order for it to work with ultrahand. I can do it myself I just need some clarification on which const mean what in extract.hpp

from my understanding, in the extract.hpp could I concatinate "const std::string& path, const std::string& outputDir" to one somehow to get the requested result? or would I need to look deeper and actually edit a different file?

**Comment by zrm9901** [comment]
btw I dont care about actually integrating ultrahand, I just want the directory to be right

**Comment by PoloNX** [comment]
Hi. You can check line 61 of this file https://github.com/PoloNX/SimpleModDownloader/blob/master/source/views/download_view.cpp
