### ISSUE TITLE
[BUG] compiling issue

### ISSUE THREAD

**Issue by zrm9901** [PoloNX/SimpleModDownloader#77]
**Describe the bug**

when building the project an error occurs or borialis fails to install

**To Reproduce**

install devkit pro and xmake, clone the repository, cd into it, and run the next command in build instructions.

**Expected behavior**

borialis should install

**Screenshots**
![image](https://github.com/user-attachments/assets/4ad402a8-a866-4c26-b97a-c72f16cda79d)

**Additional context**

everytime it gets to a different percentage before borialis fails, usually 33%, but one time it got to 66%, it is really inconsistant except for the fact that ists alway boriallis, and it never gives me that logs it says to look for

**Comment by zrm9901** [comment]
im looking at the borialis build and it seems they use cmake, is there a way to compile it with that as xmake isnt working for me

**Comment by PoloNX** [comment]
Hi ! I made several changes on the toolchain used, I will send you an updated version. Can you use xmake -vD and send me logs ?

**Comment by PoloNX** [comment]
just fixed it. Now you have to use cross platform like this :

```
(sudo) pacman -S switch-curl switch-zlib switch-glfw switch-mesa switch-glm switch-libarchive  
git clone --recursive https://github.com/PoloNX/SimpleModDownloader/
cd SimpleModDownloader
xmake f --yes -p cross -m release -a aarch64 --toolchain=devkita64
xmake
```

**Comment by zrm9901** [comment]
Worked like a charm, thanks
